# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya/RxSwift', '~> 14.0'
  pod 'RxSwift', '5.0'
  pod 'RxCocoa'
  
  target 'ChuckNorrisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckNorrisUITests' do
    # Pods for testing
  end

end
